package-lock.json, package.json, src/components/AppServicesModalProvider/ModalContext.tsx, src/components/AppServicesTable/AppServicesTable.tsx, src/components/AppServicesTable/CustomRowWrapper.tsx, src/components/AppServicesToolbar/AppServicesToolbar.tsx, tsconfig-cjs.json, tsconfig.json
The way Typescript was set up, we had a bunch of errors getting swallowed and never reported.
This uses a stricter setup for Typescript.
This is a sample of the errors we had simply updating the tsconfig.
```
❯ npm run build
> @rhoas/app-services-ui-components@0.0.0 build
> tsc -p tsconfig.json && tsc -p tsconfig-cjs.json
src/components/AppServicesModalProvider/ModalContext.tsx:57:9 - error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
57         activeModal.modalType
~~~~~~~~~~~~~~~~~~~~~
src/components/AppServicesModalProvider/ModalContext.tsx:107:17 - error TS2322: Type 'MutableRefObject<ModalRegistry>' is not assignable to type 'MutableRefObject<ModalType>'.
Type 'ModalRegistry' is not assignable to type 'ModalType'.
107 …
```
=> chore: make Typescript actually typecheck the code

.storybook/main.js, .storybook/ouia-addon/addDecorator.js, .storybook/ouia-addon/constants.js, .storybook/ouia-addon/preset.js, .storybook/ouia-addon/register.tsx, .storybook/ouia-addon/withOUIA.js, .storybook/ouia-helper.css, .storybook/preview-head.html, .storybook/preview.js
Adds an addon to Storybook to visually inspect the OUIA ids in use in the story.
Green ids are statically set, so safe to use. Red ids are autogenerated, so they probably shouldn't be used.
Ids are also listed in a panel called OUIA, with a selector that can be copy-pasted directly to Pendo and that takes into account parent OUIA ids if present.
=> chore: add a Storybook addon to ease working with OUIA ids

src/Kafka/CreateKafkaInstance/CreateKafkaInstance.stories.tsx, src/Kafka/CreateKafkaInstance/CreateKafkaInstance.tsx, src/Kafka/CreateKafkaInstance/components/CloudRegionsSelect.tsx, src/Kafka/CreateKafkaInstance/machines/CreateKafkaInstanceMachine.ts, src/Kafka/CreateKafkaInstance/machines/types.ts
Implement feedback missed  on PR https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/pull/1072/files#r817060682
Add below stories 
https://619e1921b3e38b003afeb2be-ryflrmybhy.chromatic.com/?path=/story/kafka-create-kafka-instance-create-kafka-instance--load-supported-regions-and-disabled-unsupported
https://619e1921b3e38b003afeb2be-ryflrmybhy.chromatic.com/?path=/story/kafka-create-kafka-instance-create-kafka-instance--reached-max-limit-for-trial-instance-for-supported-regions
=> fix: add reached max limit for supported regions

.github/workflows/reusable-build.yml, .github/workflows/storybook-to-pages.yml, package.json
This will run tests sequentially, but will make babel run just once instead of many times in parallel. It should improve the overall runtime especially on CI
=> chore: run jest with the --runInBand option to speed up tests on CI

locales/en/kafkaoverview-v2.json, src/AppServices/KafkaPage/__snapshots__/KafkaPageV2.test.tsx.snap, src/AppServices/KafkaPage/component/KafkaInstanceCapacityTable.tsx
Adding header to the table in Kafka overview page
=> Adding header to the table in Kafka overview page

.github/workflows/lint-pr.yml
This should give us back the commit messages check we used to have with the [Semantic Pull Request Bot](https://probot.github.io/apps/semantic-pull-requests/) that doesn't work anymore because of https://github.com/zeke/semantic-pull-requests/issues/183
=> chore: add a GH action to lint PRs to ensure usage of proper titles and commit messages to support semantic release

locales/en/metrics.json, src/Kafka/Metrics/Metrics.stories.tsx, src/Kafka/Metrics/Metrics.test.tsx, src/Kafka/Metrics/Metrics.tsx, src/Kafka/Metrics/components/CardKpi.tsx, src/Kafka/Metrics/components/MetricsLagAlert.stories.tsx, src/Kafka/Metrics/components/MetricsLagAlert.test.tsx, src/Kafka/Metrics/components/MetricsLagAlert.tsx, src/Kafka/Metrics/components/PartitionCard.stories.tsx, src/Kafka/Metrics/components/PartitionCard.test.tsx, src/Kafka/Metrics/components/PartitionCard.tsx, src/Kafka/Metrics/machines/MetricsKpiMachine.ts, src/Kafka/Metrics/storiesHelpers.ts, src/Kafka/Metrics/types.ts, src/Kafka/Metrics/useMetricsKpi.tsx
>  Add partition limit message to the topic partitions card
> Add Metrics lag message to the dashboard
> https://issues.redhat.com/browse/MGDSTRM-7799
> https://issues.redhat.com/browse/MGDSTRM-8180
kafka > Metrics > Components > Partition Card
=> feat: Add partition limit message to the topic partitions card

src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceMachine.ts, src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceProvider.tsx, src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceWithSizes.tsx, src/Kafka/CreateKafkaInstanceWithSizes/Stories/storiesHelpers.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/InstanceInfo.tsx, src/Kafka/CreateKafkaInstanceWithSizes/types.ts
[This addresses @jgiardino comment here:](https://github.com/redhat-developer/app-services-ui-components/pull/345#issuecomment-1128198906)
> This might be a bad design, but the [original design](https://docs.google.com/presentation/d/1U4j27K3L-9Ry0GPe-fcKoU48dCPlEJsfoXJUpldAY3U/edit#slide=id.g118b16caf36_0_0) was to accommodate this use case:
> 
> > If I don't have a subscription and can only create a trial instance, then I can get some idea about what options are available with a subscription.
> 
> In this use case, the size option isn't meant to show me what trial sizes are available, but rather what sizes are available with a subscription. This is why in the example above, we show that there are two options, 1 SU and 2 SU, along with a message …
=> feat: support different sizes for standard and trial instances in the create Kafka dialog with sizes

.eslintrc, locales/en/metrics.json, src/Kafka/KafkaInstanceDrawer/KafkaDetailsTab.tsx, src/Kafka/KafkaInstanceDrawer/__snapshots__/KaafkaDetailsTab.test.tsx.snap, src/Kafka/KafkaMessageBrowser/components/DateTimePicker.tsx, src/Kafka/KafkaMessageBrowser/components/FilterGroup.tsx, src/Kafka/Metrics/components/ChartLinearWithOptionalLimit.tsx, src/Kafka/Metrics/components/ChartLogSizePerPartition.tsx, src/Kafka/Metrics/components/ChartTotalBytes.tsx, src/Kafka/Metrics/components/utils.ts, src/shared/FormatDate/FormatDate.tsx
Dates are confusing. We found out that the consoledot guidelines recommend not localizing dates and showing them in the UTC timezone. The same ask has been made while demoing the message browser.
This PR changes the default behaviour of the `FormatDate` when used with either the `long` or `longWithMilliseconds` format to show the date in the UTC tz.
> e.g. `fixes #<issue number>`
> Replace this …
=> feat: show dates in the UTC tz

src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceMachine.ts, src/Kafka/CreateKafkaInstanceWithSizes/Stories/storiesHelpers.tsx
Fixes a bug where the form would show an error alert asking to fix form errors when creating trial instances and with 0 as the available quota.
=> fix: trial instances don't check for the correctness of the selected size since it can't be selected

src/AppServices/index.ts
Expose OverviewPageV2 that is missing for some reason from the index file.
=> fix: missing overviewpagev2

locales/en/metrics.json, src/Kafka/Metrics/components/MetricsLagAlert.test.tsx
Adds a missing space in the copy
=> fix: metrics typo

locales/en/create-kafka-instance-with-sizes.json
Updates the message shown in the alert under the Size field of the create Kafka instance dialog with the latest copy.
CreateKafkaInstanceWithSizes > components > FieldSizeHelperText > Tech Preview
=> fix: new message for the Tech Preview alert for the create Kafka size field

locales/en/create-kafka-instance-with-sizes.json, src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceWithSizes.tsx, src/Kafka/CreateKafkaInstanceWithSizes/Stories/FormLoad.test.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/ModalAlerts.tsx
Add dynamic duration (lifespan_seconds) instead hard code 48 hours
https://issues.redhat.com/browse/MGDSTRM-7914
- User trial kafka and open create kafka modal 
- There is a expiration time duration which is based on api field `lifespan_seconds`
Rest part adding duration in table that will be covered in kas-ui in separate PR.
https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/pull/1181
=> fix: use trial duration from the API

.storybook/manager-head.html, .storybook/preview.ts, locales/en/create-kafka-instance-with-sizes.json, locales/en/metrics.json, rollup.config.ts, src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceMachine.ts, src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceMachine.typegen.ts, src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceProvider.tsx, src/Kafka/CreateKafkaInstanceWithSizes/CreateKafkaInstanceWithSizes.tsx, src/Kafka/CreateKafkaInstanceWithSizes/Stories/FormLoad.test.tsx, src/Kafka/CreateKafkaInstanceWithSizes/Stories/FormSubmit.test.tsx, src/Kafka/CreateKafkaInstanceWithSizes/Stories/storiesHelpers.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/CloudRegionsSelect.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/FieldCloudRegion.stories.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/FieldCloudRegion.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/FieldSize.stories.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/FieldSize.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/FieldSizeHelperText.stories.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/FieldSizeHelperText.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/FormAlerts.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/InstanceInfoSkeleton.tsx, src/Kafka/CreateKafkaInstanceWithSizes/components/ModalAlerts.tsx, src/Kafka/CreateKafkaInstanceWithSizes/types.ts, src/Kafka/Metrics/components/MetricsLagAlert.test.tsx
This fixes a number of issues with the create Kafka dialog.
An instance size could be visible but not selectable for instance creation. It shows with a warning.
Trying to submit the form with a disabled size selected will transform the warning in an error.
Always display the "All available trial instances are currently in use. Try again later." message for all cases where trial instances can not be created for reasons unrelated to the user.
Aligning the modal to the top of the screen reduces the amount of layout jumping when interacting with elements that trigger changes on the visualized UI, like changing provider/region where skeletons are displayed while loading the new data.
Skeletons were tweaked to better reflect the space taken by the real …
=> fix: improve create Kafka dialog UX

src/Kafka/Metrics/components/EmptyStateNoTopics.test.tsx, src/Kafka/Metrics/components/EmptyStateNoTopics.tsx
> Add data-ouia-component-id for create topic button
> https://issues.redhat.com/browse/MGDSTRM-8695
=> chore: Add data-ouia-component-id for create topic button

src/Kafka/ManageKafkaPermissions/ManageKafkaPermisions.test.tsx, src/Kafka/ManageKafkaPermissions/ManageKafkaPermissions.tsx, src/Kafka/ManageKafkaPermissions/components/SelectAccount.stories.tsx, src/Kafka/ManageKafkaPermissions/components/SelectAccount.test.tsx, src/Kafka/ManageKafkaPermissions/components/SelectAccount.tsx
> This PR adds an option to include manual entry when selecting an account. 
This PR closes [8377](https://issues.redhat.com/browse/MGDSTRM-8377)
To view the story, navigate to ManageKafkaPermissions/Empty State
=> chore: Select user manually even if it does not exist on the list of options

src/Kafka/Metrics/Metrics.tsx, src/Kafka/Metrics/components/MetricsLagAlert.tsx, src/Kafka/Metrics/components/MetricsLayout.tsx
> Fix the padding issue for the Metrics lag alert in the metrics dashboard
> https://issues.redhat.com/browse/MGDSTRM-8180 (see the comment section for description of the issue)
https://619e1921b3e38b003afeb2be-wnmpynbryf.chromatic.com/?path=/story/kafka-metrics--all-ready&globals=withInsightsChrome:true
=> chore: Fix the padding issue for Metrics lag alert in metrics dashboard

locales/en/manage-kafka-permissions.json, src/ProofOfConcepts/TAndCModal/tAndCModal.stories.tsx, src/ProofOfConcepts/TAndCModal/tAndCModal.tsx
> Warn user that they are leaving to accept T&C. When making a Kafka Instance for the first time, they are directed to new screen where they accept the T&C flow, this caused confusion where some ignored the screen and tried to continue without accepting. 
>Story can be found in < POC > < SmallModal > < Story >
>There might need to be extra space between normal and bold text
=> chore: POC add modal to warn user when they are leaving to accept T&C

.storybook/withMas.tsx, locales/en/connection-tab.json, locales/en/kafka.json, locales/en/service-account.json, src/Kafka/KafkaInstanceDrawer/KafkaConnectionTab.tsx, src/Kafka/KafkaInstanceDrawer/KafkaConnectionTabP2.tsx, src/Kafka/ServiceAccount/components/ServiceAccountToolbar.tsx, src/test-utils.tsx
> Moving the strings in the service account translation file to the Kafka file, since the strings are related to KafkaConnectionTab.
=> chore: Remove service account translation

src/shared/ExternalLink/ExternalLink.tsx
makes the ExternalLink `className` prop optional.
cc @riccardo-forina
=> fix(ExternalLink): make className prop optional

src/shared/Table/ResponsiveTable.test.tsx, src/shared/Table/ResponsiveTable.tsx
Signed-off-by: suyash-naithani <suyash.naithani@gmail.com>
> This PR prevents the onClick handler to be called when clicking on a row kebab option, thus making sure the focus on a row does not change
> Fixes [#168](https://issues.redhat.com/browse/MGDX-168)
=> fix: Prevent focus to change on clicking row kebab options

src/Kafka/CreateKafkaInstance/Stories/storiesHelpers.tsx, src/Kafka/CreateKafkaInstance/components/BillingHelp.tsx
Added the title to the popover, and made the link not external.
=> fix: make the billing popover show a title, and make the link not external

src/shared/Table/ResponsiveTable.stories.tsx, src/shared/Table/ResponsiveTable.test.tsx, src/shared/Table/ResponsiveTable.tsx
This change adds a customizer function to ResponsiveTable so a consumer can
customize the test ID attribute for the actions kebab.  It also updates
the default test ID used so that rows can be selected by index.
I've left the return type of the customizer function constrained to just what I need, but maybe there's a better option.  Also I'm meh on the function name, so any suggestions are welcome :-)
=> feat: add a way to set the ouia id for the action cell in ResponsiveTable

src/shared/Table/TableView.tsx
This change ensures that the pagination navigation is available in
smaller screen widths by specifying the appropriate variant to the
pagination control.  It also removes the toolbar wrapping the pagination
component as it prevents the pagination control from appearing correctly
in narrow widths.
The bug in action (yes I like loud backgrounds):
with this fix applied in storybook:
=> fix: specify the pagination variants

src/Kafka/KafkaMessageBrowser/components/FilterGroup.tsx, src/Kafka/KafkaMessageBrowser/components/LimitSelector.tsx, src/Kafka/KafkaMessageBrowser/components/PartitionSelector.tsx
Add data-testid for select and dropdown component in kafka message browser
> Add data-testid as per the QE request
=> chore: Add data-testid for select and dropdown component in kafka message browser

locales/en/common.json, src/Kafka/KafkaInstanceDrawer/KafkaDetailsTab.stories.tsx, src/Kafka/KafkaInstanceDrawer/KafkaDetailsTab.tsx, src/Kafka/KafkaInstanceDrawer/__snapshots__/KafkaDetailsTab.test.tsx.snap
>Add kafka version property to the kafka details tab
fixes https://issues.redhat.com/browse/MGDSTRM-9152
https://619e1921b3e38b003afeb2be-vphlcabiyg.chromatic.com/?path=/story/kafka-kafkainstancedrawer-kafkadetailstab--standard-instance-created
=> chore: Add kafka version property to the kafka details tab

src/Kafka/index.ts
> While updating the version of app-services-ui-component in kas-ui, I noticed that some of the types are defined in the types.ts file is used in kas-ui, since it's not exported it's not available in the kas-ui
=> chore: add types to index.tsx file

README.md, src/I18n/I18nProvider.tsx
We are currently required to install `react-i18next` as a dependency of our MAS UI projects in order to translate content.
This will frequently produce two different versions of the same package in the dependency tree, like:
```
├─┬ @rhoas/app-services-ui-components@1.40.6
│ └── react-i18next@11.17.3
└── react-i18next@11.18.5
```
`I18nProvider` and `useTranslation` will then come from different versions. The result is unit tests will start failing, they will not be able to translate strings anymore.
One possible solution is to re-export `react-i18next` from `app-services-ui-components`.
This way it will live only here. Other UI projects will not have to include `react-i18next` as a dependency. Instead they will import everything from …
=> chore: re-export react-i18next 

src/Kafka/Metrics/components/ChartLogSizePerPartition.tsx, src/Kafka/Metrics/components/ChartTotalBytes.tsx
> Update kafka dashboard chart colors
> fixes https://issues.redhat.com/browse/MGDSTRM-8295
stories
https://619e1921b3e38b003afeb2be-xtsavvyxvl.chromatic.com/?path=/story/kafka-metrics-components-charttotalbytes--sample-data
https://619e1921b3e38b003afeb2be-xtsavvyxvl.chromatic.com/?path=/story/kafka-metrics-components-chartlogsizeperpartition--sample-data
=> chore: Update dashboard chart colors

src/shared/Table/ResponsiveTable.stories.tsx, src/shared/Table/ResponsiveTable.test.tsx, src/shared/Table/ResponsiveTable.tsx
Adds two new properties in the `ResponsiveTable` component for setting custom ouiaIds for `<table>` and `<tr>`s elements
You can see in the DOM that the `data-ouia-component-id` attributes will be set as specified.
=> feat: provide configurability for ouia ids of table and table rows elements in ResponsiveTable

src/Kafka/ManageKafkaPermissions/ManageKafkaPermissions.stories.tsx, src/Kafka/ManageKafkaPermissions/ManageKafkaPermissions.tsx, src/Kafka/ManageKafkaPermissions/components/AssgnPermissionsManual.stories.tsx, src/Kafka/ManageKafkaPermissions/components/AssignPermissions.tsx, src/Kafka/ManageKafkaPermissions/components/AssignPermissionsManual.tsx, src/Kafka/ManageKafkaPermissions/components/ConsumeTopicShortcut.stories.tsx, src/Kafka/ManageKafkaPermissions/components/ConsumeTopicShortcut.tsx, src/Kafka/ManageKafkaPermissions/components/ProduceTopicRow.tsx, src/Kafka/ManageKafkaPermissions/components/ProduceTopicShortcut.stories.tsx, src/Kafka/ManageKafkaPermissions/components/ProduceTopicShortcut.tsx, src/Kafka/ManageKafkaPermissions/components/ResourceName.stories.tsx, src/Kafka/ManageKafkaPermissions/components/ResourceName.test.tsx, src/Kafka/ManageKafkaPermissions/components/ResourceName.tsx, src/shared/AsyncTypeaheadSelect/AsyncTypeaheadSelect.stories.tsx, src/shared/AsyncTypeaheadSelect/AsyncTypeaheadSelect.test.tsx, src/shared/AsyncTypeaheadSelect/AsyncTypeaheadSelect.tsx
Signed-off-by: suyash-naithani <suyash.naithani@gmail.com>
While integrating the acls, we realised that an async call for the topics and consumer groups is not needed. This PR removes the async props from the acl to simply return an array of string
=> chore: Remove async call for acl topics

locales/en/kafkaoverview-v3.json, src/AppServices/KafkaPageV3.test.tsx, src/AppServices/KafkaPageV3.tsx, src/AppServices/__snapshots__/KafkaPageV3.test.tsx.snap, src/Kafka/KafkaInstanceDrawer/KafkaDetailsTab.stories.tsx, src/Kafka/KafkaInstanceDrawer/KafkaDetailsTab.tsx, src/Kafka/KafkaInstanceDrawer/__snapshots__/KafkaDetailsTab.test.tsx.snap
> Remove coming soon text from GCP on the overview page
> https://issues.redhat.com/browse/MGDSTRM-9399
=> chore: Remove coming soon text from GCP on overview page

src/Kafka/ManageKafkaPermissions/ManageKafkaPermissions.tsx
Update ACL prop type to not be optional
Fix a bug when creating a resource type of kind 'Kafka Instance'
=> chore: Update ACL types

src/Kafka/ManageKafkaPermissions/components/SelectAccount.tsx
The dropdown of select account when open covers the entire page, make the dropdown height smaller and more in line with the current height of the select on our app
=> chore: Set max height for select account

.github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/publish-release.yml, .github/workflows/reusable-build.yml
Hopefully fixes the failing GH actions
=> chore: upgrade node version for all gh actions to the latest LTS

src/AppServices/OverviewPageV2.tsx, src/AppServices/OverviewPageV3.tsx, src/AppServices/OverviewPageV4.tsx, src/AppServices/__snapshots__/OverviewPageV2.test.tsx.snap, src/AppServices/__snapshots__/OverviewPageV4.test.tsx.snap
This change removes the service preview label from the Connectors service card.
from:
to:
=> feat: MGDCTRS-1887 remove service preview label

src/AppServices/OverviewPageV4.tsx, src/AppServices/__snapshots__/OverviewPageV4.test.tsx.snap
We have a request from the consoledot team and execs to remove the labels since they are outdated. This page will likely be going away within the next few months so this is just a quick fix to remove outdated info.
=> fix: Remove labels and groups from cards

.github/workflows/lint-pr.yml, .github/workflows/main.yml, .github/workflows/reusable-build.yml, .github/workflows/storybook-to-pages.yml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
=> chore: Pin 3rd-party actions to SHA1

src/Kafka/ManageKafkaPermissions/components/ResourceName.stories.tsx, src/Kafka/ManageKafkaPermissions/components/__snapshots__/ConsumeTopicShortcut.test.tsx.snap, src/Kafka/ManageKafkaPermissions/components/__snapshots__/ProduceTopicShortcut.test.tsx.snap, src/shared/AsyncTypeaheadSelect/AsyncTypeaheadSelect.tsx
- We need to persist the input value of the component on blur. Add props to give the user freedom to decide how he wants to consume this component. 
- We don't need to hard code the width for a shared component 
Updated snapshots since the hard coded width value was removed. Tested on storybook and everything works and looks as expected
=> chore: Add props for shared async select

src/AppServices/OverviewPageV4.stories.tsx, src/AppServices/OverviewPageV4.test.tsx, src/AppServices/OverviewPageV4.tsx, src/AppServices/__snapshots__/OverviewPageV4.test.tsx.snap
> Update overview page as per the [doc](https://docs.google.com/presentation/d/1Cadn2Npxsr_-unKtGxX24TK0gIFLo65L7sPjon0uyMQ/edit#slide=id.g23a3841a301_0_0)
> related to issue https://issues.redhat.com/browse/MGDSTRM-11169 
=> chore: update overview page
