src/components/Metrics/Metrics-i18n.json
src/components/Metrics/Metrics.tsx
src/components/Metrics/components/CardUsedDiskSpace.tsx
src/components/Metrics/useKafkaInstanceMetrics.tsx

Adding client connections chart to the dashboard

Adding client connections chart to the dashboard

---

src/components/DevelopmentPreview/DevelopmentPreview-i18n.json
src/components/DevelopmentPreview/DevelopmentPreview.css
src/components/DevelopmentPreview/DevelopmentPreview.stories.tsx
src/components/DevelopmentPreview/DevelopmentPreview.tsx

Add story for development preview

feat: Add story for development preview

---

package-lock.json
package.json
src/Metrics/components/FilterByTopic.css
src/Metrics/components/FilterByTopic.stories.tsx
src/Metrics/components/FilterByTopic.tsx

Follow up to https://github.com/redhat-developer/app-services-ui-components/pull/70 (that I somehow messed)

fix: FilterByTopic can handle topics with very long names

---

.storybook/preview.js
App.css
locales/en/datascienceoverview.json
src/DataSciencePage/DataSciencePage.stories.tsx
src/DataSciencePage/DataSciencePage.tsx
src/DataSciencePage/index.ts
src/OverviewPage/OverviewPage.tsx
src/index.ts

Add visual component for DataScience Page and write stories

feat: Add visual component for DataScience Page and write stories

---

.storybook/preview.js
App.css
locales/en/apimgmtoverview.json
src/APIManagement/APIManagementPage.stories.tsx
src/APIManagement/APIManagementPage.tsx
src/APIManagement/index.ts
src/index.ts

Add visual component for API Management and write stories

feat: Add visual component for API Management and write stories

---

src/OverviewPage/OverviewPage.tsx

In https://github.com/redhat-developer/app-services-ui/pull/287, the app-services-ui is using assets in this repo, so the changes made in https://github.com/redhat-developer/app-services-ui/pull/250 of adding OUIA id should be moved here.

fix: add data-ouia-component-id to some elements

---

src/CreateKafkaInstance/CreateKafkaInstance.tsx
src/OverviewPage/OverviewPage.tsx

Based on the updates of the design input in the Miro board here: https://miro.com/app/board/uXjVOeGbzSM=/?utm_source=notification&utm_medium=email&utm_campaign=daily-updates&utm_content=go-to-board, add new `ouiaId` to create kafka instance modal and try kafka button at the overview page.

fix: update OUIA id

---

locales/en/overview.json
src/AppServices/OverviewPage/__snapshots__/OverviewPage.test.tsx.snap

feat: Update RHODA overview card text

---

src/Kafka/CreateKafkaInstance/CreateKafkaInstance.tsx

Update the client connections limit in the create modal

Update the client connection limit

---

src/Kafka/CreateKafkaInstance/CreateKafkaInstance.test.tsx
src/Kafka/CreateKafkaInstance/CreateKafkaInstance.tsx

https://issues.redhat.com/browse/MGDX-77

fix: add missing data-ouia-component-id

---

locales/en/create-kafka-instance.json
src/Kafka/CreateKafkaInstance/CreateKafkaInstance.css
src/Kafka/CreateKafkaInstance/CreateKafkaInstance.stories.tsx
src/Kafka/CreateKafkaInstance/CreateKafkaInstance.test.tsx
src/Kafka/CreateKafkaInstance/CreateKafkaInstance.tsx
src/Kafka/CreateKafkaInstance/components/CloudProviderTiles.css
src/Kafka/CreateKafkaInstance/components/CloudProviderTiles.tsx
src/Kafka/CreateKafkaInstance/components/FormAlerts.tsx
src/Kafka/CreateKafkaInstance/components/InstanceInfo.stories.tsx
src/Kafka/CreateKafkaInstance/components/InstanceInfo.test.tsx
src/Kafka/CreateKafkaInstance/components/InstanceInfo.tsx
src/Kafka/CreateKafkaInstance/components/ModalAlerts.tsx
src/Kafka/CreateKafkaInstance/components/__snapshots__/InstanceInfo.test.tsx.snap
src/shared/DeleteModal/DeleteModal.test.tsx
src/test-utils.tsx

Adds tests for all stories about `CreateKafkaInstance`

chore: improve test coverage of CreateKafkaInstance and components

---

.github/pull_request_template.md

Adding PR template to the Repository

Adding PR template to the Repository

---

src/shared/FormatDate/FormatDate.tsx

> Show time to expiry in months if days are greater than 30 to display time to expiry for service registry which is 2 months

Add option to display expiry time in months

---

locales/en/kafka.json
src/Kafka/KafkaInstanceDrawer/KafkaConnectionTab.stories.tsx
src/Kafka/KafkaInstanceDrawer/KafkaConnectionTab.tsx
src/Kafka/KafkaInstanceDrawer/__snapshots__/kafkaConnectionTab.test.tsx.snap

Add Kafka admin URL section in the connection details tab
https://issues.redhat.com/browse/MGDSTRM-7015
design doc - https://docs.google.com/document/d/1GeZnF8d8k9esakNSlWC_2FUVbZWLnNFHedracLMYFTw/edit
kafka > kafka Instance Drawer > kafka Connect Tab > Connection Tab

feat: Add kafka admin URL section in the connection details tab

---

.storybook/InsightsChromeLayout.css
.storybook/InsightsChromeLayout.tsx
src/Kafka/KafkaMessageBrowser/KafkaMessageBrowser.css
src/Kafka/KafkaMessageBrowser/KafkaMessageBrowser.tsx
src/shared/Table/TableView.tsx

Make use of `OuterScrollContainer` and `InnerScrollContainer` to properly flag the scrollable area we want for the tables.
The `TableView` component does it automatically. Also updates the `KafkaMessageBrowser` component to leverage the same behavior.

fix: make the TableView scrollable to better work in the MAS layout

---

src/Kafka/ConsumerGroups/components/ConsumerGroupTable.stories.tsx
src/Kafka/ConsumerGroups/components/ConsumerGroupTable.test.tsx
src/Kafka/ConsumerGroups/components/ConsumerGroupTable.tsx
src/Kafka/index.ts

> Update the storybook to show the kebab menu at the topic level and Kafka level 
https://issues.redhat.com/browse/MGDSTRM-7854
Kafka > Consumer groups > Components > Default consumer group

chore: Update the storybook to show the kebab menu at the topic level and Kafka level 

---

locales/en/create-kafka-instance-with-sizes.json
locales/en/create-kafka-instance.json
src/Kafka/CreateKafkaInstance/CreateKafkaInstance.tsx
src/Kafka/CreateKafkaInstance/components/InstanceInfo.stories.tsx
src/Kafka/CreateKafkaInstance/components/InstanceInfo.tsx
src/Kafka/CreateKafkaInstance/components/__snapshots__/InstanceInfo.test.tsx.snap
src/Kafka/CreateKafkaInstanceWithSizes/components/__snapshots__/InstanceInfo.test.tsx.snap
src/Kafka/KafkaMessageBrowser/components/FilterGroup.tsx

Does change limits for kafka instances.

fix: changed limits for kafka instance

---

src/Kafka/KafkaInstanceDrawer/KafkaDetailsTab.stories.tsx
src/Kafka/KafkaInstanceDrawer/KafkaDetailsTab.tsx
src/Kafka/KafkaInstanceDrawer/KafkaSizeSkeleton.tsx

add skeleton for kafka details page
> e.g. `fixes #<issue number>`

fix: add skeleton for kafka details page

---

package-lock.json
package.json
renovate.json
setupJest.ts
src/AppServices/components/MarketingPage.tsx
src/shared/EmptyState/EmptyState.tsx

Remove unused dependencies from the project.

chore: remove unused deps

---

locales/en/common.json
src/Kafka/ConsumerGroups/components/DeleteConsumerGroup.stories.tsx
src/Kafka/ConsumerGroups/components/DeleteConsumerGroup.test.tsx
src/Kafka/ConsumerGroups/components/DeleteConsumerGroup.tsx
src/shared/DeleteModal/DeleteModal.tsx

> Add storybook Component for consumer Group delete modal
> Kafka > ConsumerGroups > Components > DeleteConsumerGroup

feat: Consumer Group delete modal

---

src/Kafka/CreateKafkaInstanceWithSizes/components/InstanceInfo.tsx
src/Kafka/CreateKafkaInstanceWithSizes/components/InstanceInfoSkeleton.tsx
src/Kafka/CreateKafkaInstanceWithSizes/components/__snapshots__/InstanceInfo.test.tsx.snap

Added data-testid for UI E2E tests.

fix: Added data-testid to kafka size in details section

---

src/Kafka/KafkaInstanceDrawer/KafkaConnectionTab.tsx
src/Kafka/KafkaInstanceDrawer/KafkaConnectionTabP2.tsx
src/Kafka/KafkaInstanceDrawer/__snapshots__/kafkaConnectionTab.test.tsx.snap
src/Kafka/KafkaInstanceDrawer/__snapshots__/kafkaConnectionTabP2.test.tsx.snap
src/Kafka/KafkaInstanceDrawer/kafkaConnectionTab.test.tsx
src/Kafka/KafkaInstanceDrawer/kafkaConnectionTabP2.test.tsx

> Add data-testid for create service account

chore: Add data-testid for create service account

---

.storybook/withMas.tsx
locales/en/overview-v3.json
src/AppServices/OverviewPageV3.stories.tsx
src/AppServices/OverviewPageV3.tsx
src/AppServices/__snapshots__/OverviewPageV2.test.tsx.snap
src/AppServices/index.ts
src/test-utils.tsx

Reverts redhat-developer/app-services-ui-components#485

chore: revert "chore: Add kafkaPagev3 to index.ts file"

---

locales/en/kafka.json
src/Kafka/Settings/Settings.css
src/Kafka/Settings/Settings.stories.tsx
src/Kafka/Settings/Settings.test.tsx
src/Kafka/Settings/Settings.tsx
src/Kafka/Settings/components/SettingsAlert.stories.tsx
src/Kafka/Settings/components/SettingsAlert.tsx
src/Kafka/Settings/components/index.ts
src/Kafka/Settings/index.ts
src/Kafka/Settings/types.ts
src/Kafka/index.ts

> Create UI for the settings tab
> fixes https://issues.redhat.com/browse/MGDSTRM-8810
**Where to find story**
Interactive story
https://619e1921b3e38b003afeb2be-giggariile.chromatic.com/?path=/story/kafka-settings--interactive-example&globals=withInsightsChrome:true

feat: Settings tab

---

src/Kafka/KafkaInstanceDrawer/KafkaConnectionTabP1.stories.tsx
src/Kafka/KafkaInstanceDrawer/KafkaConnectionTabP1.tsx

> Remove unused props
related to issue https://issues.redhat.com/browse/MGDSTRM-9476

chore: remove unused props

---

src/AppServices/index.ts

> Add Kafka overview page v3 to index file to integrate AWS Marketplace

chore: Add Kafka overview page v3 to index file

---

package-lock.json
src/Kafka/CreateKafkaTopic/components/CreateTopicWizard.test.tsx

Signed-off-by: suyash-naithani <suyash.naithani@gmail.com>
> Fix failing tests on the repo by adding package-lock file and removing some tests

chore: Fix test

---

package-lock.json

> Fix package-lock file related to patternfly version mismatch

chore: Package lock file update

---

src/Kafka/Settings/Settings.stories.tsx
src/Kafka/Settings/Settings.test.tsx
src/Kafka/Settings/Settings.tsx
src/Kafka/Settings/components/SettingsAlert.tsx

- Improve Settings 
- Cover missing use case
- Remove unused code and stories

fix: improve settings code

---

package-lock.json
package.json

> update peer dependencies in the package.json file

chore: Fix build issue

---

src/AppServices/index.ts
src/Kafka/KafkaInstanceDrawer/KafkaConnectionTabP2.stories.tsx
src/Kafka/KafkaInstanceDrawer/KafkaConnectionTabP2.tsx
src/Kafka/KafkaInstanceDrawer/index.ts

> Add link to the API document 
> Export overviewpage4 in index.ts file
. fixes https://issues.redhat.com/browse/MGDSTRM-9115

chore: Add API documentation link to the connection tab

---

src/Kafka/Metrics/components/MetricsLayout.tsx
src/Kafka/Settings/Settings.tsx

> Fix layout issue on settings and dashboard tab
> fixes https://issues.redhat.com/browse/MGDSTRM-9805
following are the screenshot of how the layout is in the actually UI after removing the page section

chore: fix layout issue in dashbard and settings tab

---

src/Kafka/KafkaMessageBrowser/KafkaMessageBrowser.test.tsx
src/Kafka/KafkaMessageBrowser/KafkaMessageBrowser.tsx
src/Kafka/KafkaMessageBrowser/MessageBrowserMachine.ts
src/Kafka/KafkaMessageBrowser/MessageBrowserMachine.typegen.ts
src/Kafka/KafkaMessageBrowser/components/FilterGroup.tsx

Signed-off-by: suyash-naithani <suyash.naithani@gmail.com>
> This PR fixes the following epoch timestamp issue
1. The input field was behaving strange on backspace by not allowing the user to delete the value in the field
2. On increasing the value by what should be 1, the value was getting increased to a random value 
> https://issues.redhat.com/browse/MGDSTRM-8724

chore: Fix Epoch timestamp filter on message browser

---

src/Kafka/Metrics/components/MetricsLayout.tsx
src/Kafka/Settings/Settings.tsx

> fix padding issue in settings and dashboard page.
>  fixes https://issues.redhat.com/browse/MGDSTRM-9805

chore: fix padding issue in settings and dashboard page

---

locales/en/manage-kafka-permissions.json
src/Kafka/ManageKafkaPermissions/components/ReviewPermissionsTable.tsx

> Add aria-label to review the permission table

chore: Add aria-label to review permission table

---

locales/en/common.json
locales/en/topic.json
src/Kafka/CreateKafkaTopic/CreateTopicPage.stories.tsx
src/Kafka/CreateKafkaTopic/components/CoreConfiguration.tsx
src/Kafka/CreateKafkaTopic/components/CustomRetentionMessage.tsx
src/Kafka/CreateKafkaTopic/components/CustomRetentionSize.tsx
src/Kafka/CreateKafkaTopic/components/StepMessageRetention.tsx
src/Kafka/CreateKafkaTopic/types.ts
src/Kafka/KafkaTopics/KafkaTopics.tsx
src/Kafka/KafkaTopics/components/EmptyStateNoTopic.stories.tsx
src/Kafka/KafkaTopics/components/EmptyStateNoTopic.test.tsx
src/Kafka/KafkaTopics/components/EmptyStateNoTopic.tsx
src/Kafka/KafkaTopics/components/TopicsTable.stories.tsx
src/Kafka/KafkaTopics/components/TopicsTable.test.tsx
src/Kafka/KafkaTopics/components/TopicsTable.tsx
src/Kafka/KafkaTopics/components/index.ts
src/Kafka/KafkaTopics/index.ts
src/Kafka/KafkaTopics/kafkaTopics.stories.tsx
src/Kafka/KafkaTopics/types.ts
src/Kafka/index.ts
src/Kafka/types.ts
src/shared/EmptyState/EmptyStateNoResults.stories.tsx
src/shared/EmptyState/EmptyStateNoResults.test.tsx
src/shared/EmptyState/EmptyStateNoResults.tsx
src/shared/EmptyState/__snapshots__/EmptyStateNoResults.test.tsx.snap
src/shared/EmptyState/index.ts
src/shared/Table/ResponsiveTable.tsx
src/shared/TableToolbar/SearchInput.tsx

> Use the responsive table for the topics list view
fixes https://issues.redhat.com/browse/MGDSTRM-9359
Link to story - https://619e1921b3e38b003afeb2be-lajvitpdte.chromatic.com/?path=/story/kafka-kafkatopics-kafkatopics--kafka-topics

feat: Topic table

---

src/Kafka/ConsumerGroups/components/index.ts

> export consumer group components

chore: export consumer group components

---

src/AppServices/__snapshots__/KafkaPageV2.test.tsx.snap
src/AppServices/__snapshots__/KafkaPageV3.test.tsx.snap
src/AppServices/components/KafkaInstanceCapacityTable.tsx

> Update client connection limit on kafka overview page
> fixes https://issues.redhat.com/browse/MGDSTRM-10066

chore: Update client connect limit on kafka overview

---

src/Kafka/KafkaTopics/KafkaTopics.tsx
src/Kafka/KafkaTopics/index.ts
src/Kafka/KafkaTopics/kafkaTopics.stories.tsx
src/Kafka/KafkaTopics/types.ts
src/Kafka/KafkaTopics/useTopicLabels.ts

> Sorting is not working as expected in the topic table in the kafka-ui due to the labels mismatch 
> PR fixes the sorting issue in the topics table

chore: fix sorting in topic table

---

src/Kafka/KafkaTopics/KafkaTopics.tsx
src/Kafka/KafkaTopics/kafkaTopics.stories.tsx

> fix topic table loading issue

chore: fix topic table loading

---

.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/publish-release.yml
.github/workflows/reusable-build.yml

Reverts redhat-developer/app-services-ui-components#609

chore: Revert "chore: upgrade node version for all gh actions to the latest LTS"

---

.github/workflows/reusable-build.yml
package.json

Trying to improve the speed of the step that tests the Storybook stories

chore: try to improve Storybook testing

---

src/Kafka/ManageKafkaPermissions/ManageKafkaPermissions.test.tsx
src/shared/Table/TableView.stories.tsx
src/shared/Table/TableView.test.tsx
src/shared/Table/TableView.tsx

> We have the option to show toolbar in responsive table but it was not showing up because of a missing prop.
> Ad the missing prop and expand on the type of `ToolbarAction` to allow sending dropdown values and to enable/disable the dropdown items

chore: Add kebab in the toolbar

---

src/shared/Table/TableView.stories.tsx
src/shared/Table/TableView.tsx

>Add props for aria-label for table toolbar and kebab options

chore: Add aria-label props for toolbar

---

src/shared/Table/TableView.stories.tsx
src/shared/Table/TableView.tsx

Remove the aria-label and instead use ouiaid for testing toolbar and kebab dropdown

chore: Add ouia id to toolbar and kebab option

---

src/shared/DeleteModal/DeleteModal.stories.tsx
src/shared/DeleteModal/DeleteModal.tsx

> Pressing Enter key refreshes the page while filling in the name in the delete modal
> https://issues.redhat.com/browse/MGDX-430

chore: fix refresh page issue when enter key is pressed

---

src/shared/Table/TableView.tsx

> Replace this with a quick explanation of what's included here. 
> e.g. `fixes #<issue number>`
fixes: #632 
Go to the toolbar tableview story and set the action to false

fix: properly distinguish between primary and secondary buttons in the TableView toolbar
